# Generated by Django 3.0.7 on 2020-10-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('religion', models.CharField(max_length=20)),
                ('dp', models.ImageField(upload_to='')),
                ('address', models.TextField()),
                ('aadhar', models.PositiveIntegerField()),
                ('pan', models.CharField(max_length=10)),
                ('ebill', models.FileField(upload_to='')),
            ],
        ),
    ]
