# Generated by Django 3.0.7 on 2020-10-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20201006_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='dp',
            field=models.FileField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='ebill',
            field=models.FileField(upload_to='electricitybills'),
        ),
    ]
