# Generated by Django 3.0.7 on 2020-10-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20201006_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='dp',
            field=models.FileField(upload_to='vote/photos/'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='ebill',
            field=models.FileField(upload_to='vote/electricitybills/'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Rather Not Say')], max_length=30),
        ),
        migrations.AlterField(
            model_name='voter',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Islam', 'Islam'), ('Christian', 'Christian'), ('Jain', 'Jain'), ('Buddhist', 'Buddhist'), ('Sikh', 'Sikh'), ('Others', 'Others')], max_length=20),
        ),
    ]
